### ISSUE TITLE
Menerjemahkan bagian Pendahuluan

### ISSUE THREAD

**Issue by zaaldian** [progit/progit2-id#10]
Halo semua,

saya berencana akan menerjemahkan bagian Pendahuluan (`introduction.asc`) pada Jum'at 3 Februari 2017. Apabila ada yang sedang mengerjakan bagian tersebut, mohon untuk memberitahukan hal tersebut.

**Comment by liffindra** [comment]
Halo semua,

Saya telah membuat pull request untuk bagian Pendahuluan pada #11

**Comment by baguzzzaji** [comment]
Menurut saya untuk istilah Version Control System (VCS), dan istilah-istilah lainnya tidak usah kita terjemahkan saja karena belum ada istilah resmi bahasa Indonesia juga agar tidak membingungkan pembaca nantinya.

**Comment by indrakaw** [comment]
GitHub punya fitur review yang mebolehkan partisipan komentar/memberimasukan pada setiap baris kode pada PR. Jadi anda tidak perlu mengajuka issue untuk sebuah PR.

**Comment by liffindra** [comment]
@baguzzzaji hmm.. begitu.. ada benarnya juga. Karena saya lihat di panduan penulisan Bahasa Indonesia, kalau memang sering disebut seperti itu, bisa saja tidak diterjemahkan. Yang penting, pembaca masih dapat memahami.

@indrakaw siap. Saya hanya belum paham, bagaimana jika ada orang lain yang juga menerjemahkan bagian yang sama? Apakah bisa digabung, atau digunakan salah satu.
