### ISSUE TITLE
Join translation (en-ID)

### ISSUE THREAD

**Issue by anaufalm** [progit/progit2-id#15]
Hi, I wanna join this translation. I will translate this book from original file (english) in folder progit/progit2 into Indonesian in folder progit/progit2-id. If you allow me to translate this book, I will start after you approve my proposal (reply to this issue). I will translate gradually and continuously until everything I translate.
thanks.

Regard.

**Comment by jnavila** [comment]
@baguzzzaji 
@anaufalm is willing to help for this translation.

**Comment by baguzzzaji** [comment]
Hi @anaufalm. Anyone who willing to help to translate the book is welcome. Before you start translating, make sure to open a new issue on which chapters you are going to translate.

**Comment by iqbaladan** [comment]
Hi @baguzzzaji, this would be great chance to participate in this translation project.  I would like to lend you my hand in translating this book into Bahasa Indonesia.

**Comment by baguzzzaji** [comment]
@iqbaladan awesome! I'm happy to hear that. Let's finish translating this book together in 2018 \o/.

**Comment by anaufalm** [comment]
I'm glad to hear that. I'll start translate now, let's finish translating this book together \m/

**Comment by yhandot** [comment]
Hello team progit-id

I am translator indonesian language,
May I also translate this project into Indonesian? I want to help this project. Thank you for attention!

**Comment by anaufalm** [comment]
:3 :3 
Bagi tugas aja mod, jangan sampai duplikat. Kalau mau translate open issue dulu, bab berapa yang mau dikerjakan. Terima kasih

**Comment by baguzzzaji** [comment]
@yhandot please check #19 and choose any files you want to start working on.
