### ISSUE TITLE
Join to translate English into Indonesian

### ISSUE THREAD

**Issue by mohdhaekal** [progit/progit2-id#18]
Hello,
I am an Indonesian translator Can I join this project, I am contacting you to find out if you want some Simplified (ID) translation translation.
Waiting for your reply.

**Comment by baguzzzaji** [comment]
Hi @mohdhaekal,
Please check #19 and chose which files you want to translate.

**Comment by mohdhaekal** [comment]
I want to translate the third order ( 1-distributed-git.asc)
