### ISSUE TITLE
Translate LICENSE, README, and update status.json.

### ISSUE THREAD

**Issue by baguzzzaji** [progit/progit2-id#2]
Starting to translate Progit 2 to Bahasa Indonesia

**Comment by dikiaap** [comment]
Mungkin bagus di taruh di organisasi https://github.com/GitIndonesia. biar menghindari konflik PR untuk pertama kolaborasi.

**Comment by indrakaw** [comment]
:+1: untuk update.

**Comment by dikiaap** [comment]
Hem, PR nya udah lebih dari 2 minggu. :|

**Comment by indrakaw** [comment]
Bump @schacon and @ben, for merge pull request. 
It has been 2 years since the last commit, tbh. I'm worried.

**Comment by baguzzzaji** [comment]
Halo semua :D
