### ISSUE TITLE
Bergabung menjadi penerjemah

### ISSUE THREAD

**Issue by liffindra** [progit/progit2-id#5]
Halo, semua

ini adalah pertama kalinya saya ikut bekerja bersama dalam proyek sumber terbuka. Saya mulai dengan menambahkan nama saya pada daftar penerjemah.

**Comment by indrakaw** [comment]
Orang bijak berkata: _"Tiada imbalan tanpa ada hasil"_
Sebelum mencantumkan nama, anda harus berkontribusi dengan melakukan pengembahan.

Kembali lagi bila ada hasil!

**Comment by liffindra** [comment]
Baik, @indrakaw . Mohon maaf apabila telah lancang atau menyinggung Anda. Seperti yang telah saya nyatakan sebelumnya, ini adalah pertama kalinya saya bekerja bersama dalam proyek sumber terbuka. Jadi, mohon maaf dan maklum apabila saya melakukan kesalahan.

Sebelumnya saya telah meminta bimbingan dari @baguzzzaji melalui obrolan di Slack, saran pertama adalah dengan mencoba menambahkan nama saya di daftar penerjemah di bagian README. Langkah-langkahnya, menurut @baguzzzaji adalah:

1. membuat issue dulu (karena saya baru pertama mencoba, saya beri judul seperti judul issue)
2. tambahkan nama saya di README, kemudian push ke repository saya
3. buat pull request

Mungkin maksud dari @baguzzzaji adalah agar saya memahami terlebih dahulu bagaimana alur dan tata cara bekerja bersama pada proyek sumber terbuka.

Demikian penjelasan dari saya.

**Comment by indrakaw** [comment]
i c

**Comment by baguzzzaji** [comment]
Maaf kang @indrakaw, memang awalnya saya yang meminta untuk kang @liffindra untuk edit file README dahulu sebelum yang lain. 

Karena belum ada panduan untuk melakukan penerjemahan dan kang @liffindra belum pernah menggunakan Github, jadi saya pikir yang paling mudah untuk dilakukan pertama kali itu edit file README. 

Mungkin kita bisa bersama-sama membuat panduan agar hal ini tidak terjadi lagi di masa mendatang.

**Comment by liffindra** [comment]
Saya setuju dengan Kang @baguzzzaji. Ada baiknya kita membuat panduan untuk mulai menerjemahkan bagi orang-orang yang ingin membantu menerjemahkan.

Jujur, kemarin saya agak kebingungan untuk mulai menerjemahkan :laughing: Ternyata perlu pasang `asciidoctor` dulu dan memasang beberapa _dependency_.
