### ISSUE TITLE
Tambah Panduan Penerjemahan

### ISSUE THREAD

**Issue by baguzzzaji** [progit/progit2-id#8]

**Comment by liffindra** [comment]
Mungkin ada baiknya apabila juga mempelajari [Pedoman Umum Ejaan Bahasa Indonesia](badanbahasa.kemdikbud.go.id/lamanbahasa/sites/default/files/PUEBI.pdf). Karena, saya sempat menemukan kesalahan penulisan pada salah satu berkas :laughing:
